### ISSUE TITLE
Number references from bottom to top

### ISSUE THREAD

**Issue by Gabriel-p** [bjfletcher/convert-markdown-inlined-links-to-references#1]
Currently the code numbers the references from top to bottom, that is the first inline link gets the number [1], then [2], etc until the last one.

But if the file is to be expanded in the future (ie: more references added), it makes more sense to have the top link numbered _last_.

Could this be made an option? Perhaps a `--reverse` flag?

**Comment by bjfletcher** [comment]
Hello, @Gabriel-p! Sorry was out showing Mum more of Wimbledon. :)

Reverse numbering, I've added this capability in comments here:

https://github.com/bjfletcher/convert-markdown-inlined-links-to-references/blob/master/main.js#L20

which can be uncommented (with the other one commented out) for numbering in reverse.

HTH :)

**Comment by Gabriel-p** [comment]
Awesome, thank you very much!

**Comment by bjfletcher** [comment]
You're welcome.
